# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node-test:
    uses: ./.github/workflows/part_node_test.yaml

  docker-build:
    uses: ./.github/workflows/part_docker_build.yaml

  docker-test:
    needs: docker-build
    uses: ./.github/workflows/part_docker_test.yaml
    with:
      artifact_name: ${{ needs.docker-build.outputs.artifact_name }}
      image_name: ${{ needs.docker-build.outputs.image_name }}

  docker-push:
    needs: [docker-build, docker-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: ./.github/workflows/part_docker_push.yaml
    with:
      artifact_name: ${{ needs.docker-build.outputs.artifact_name }}
      image_name: ${{ needs.docker-build.outputs.image_name }}
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
